VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDPLE5PDQGACXEOYOKILPAEIBSV5C3YVDFSHUAFHQ5SADENFSMBLDRJA",
"GDM3QS4ZRZRTKD2PPBTSTOLNGO3DGYWONB47SW3JMDHWSIZL3MSTHOEW"
]

[DOCUMENTATION]
ORG_NAME="XTZM"
ORG_URL="https://stellarkortex.io/"
ORG_LOGO="https://stellarmint.io/wp-content/uploads/2021/09/РёР·РѕР±СЂР°Р¶РµРЅРёРµ_2021-09-16_125243.png"
ORG_DESCRIPTION="Kortex"
ORG_PHYSICAL_ADDRESS="Calle 55 No. 10, , Floors 7-8, 110221, Bogota D.C. Colombia"
ORG_PHONE_NUMBER="+5713905053"
ORG_OFFICIAL_EMAIL="kortextoken@gmail.com"

[[CURRENCIES]]
code="XTZM"
issuer="GDPLE5PDQGACXEOYOKILPAEIBSV5C3YVDFSHUAFHQ5SADENFSMBLDRJA"<br/>
display_decimals=7
fixed_number=10000000
is_asset_anchored=false
name="Kortex"
desc="Kortex. Total supply only 50M."
conditions="Total supply only 50M."
image="https://stellarmint.io/wp-content/uploads/2021/09/РёР·РѕР±СЂР°Р¶РµРЅРёРµ_2021-09-16_125243.png"

# XTZM (XTZM) Token was issued using the open and inclusive Stellar blockchain network.
# Home Domain: kortex.stellarmint.io
# XTZM Token